<MainLayout>:
    orientation: "vertical"
    padding: 20
    spacing: 20

    Label:
        id: altitude
        text: "Altitude"
        font_size: 50

    Label:
        id: pressure
        text: "Pressure"
        font_size: 40

    Button:
        id: start_btn
        text: "Start"
        on_press: root.show_input_popup()

    Button:
        id: stop_btn
        text: "Stop"
        on_press: root.stop()
        disabled: True